/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BloodRouteImport } from './routes/blood'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DateConverterRouteImport } from './routes/date-converter'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ElectionRouteImport } from './routes/election'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PatroRouteImport } from './routes/patro'
import { Route as PreetiRouteImport } from './routes/preeti'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DirectoryIdRouteImport } from './routes/directory.$id'
import { Route as ElectionIdRouteImport } from './routes/election.$id'
import { Route as ElectionEmbedRouteImport } from './routes/election.embed'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as MemberIdRouteImport } from './routes/member.$id'
import { Route as PoliticianIdRouteImport } from './routes/politician.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ElectionLocalIdRouteImport } from './routes/election.local.$id'
import { Route as ElectionPoliticianIdRouteImport } from './routes/election.politician.$id'
import { Route as ShareImageArticleSlugRouteImport } from './routes/share-image.article.$slug'
import { Route as ShareImageDirectoryIdRouteImport } from './routes/share-image.directory.$id'
import { Route as ShareImageGallerySlugRouteImport } from './routes/share-image.gallery.$slug'
import { Route as ApiOgArticleSlugRouteImport } from './routes/api/og.article.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodRoute = BloodRouteImport.update({
  id: '/blood',
  path: '/blood',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DateConverterRoute = DateConverterRouteImport.update({
  id: '/date-converter',
  path: '/date-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionRoute = ElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PatroRoute = PatroRouteImport.update({
  id: '/patro',
  path: '/patro',
  getParentRoute: () => rootRouteImport,
} as any)
const PreetiRoute = PreetiRouteImport.update({
  id: '/preeti',
  path: '/preeti',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIdRoute = DirectoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DirectoryRoute,
} as any)
const ElectionIdRoute = ElectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ElectionRoute,
} as any)
const ElectionEmbedRoute = ElectionEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ElectionRoute,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleryRoute,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticianIdRoute = PoliticianIdRouteImport.update({
  id: '/politician/$id',
  path: '/politician/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionLocalIdRoute = ElectionLocalIdRouteImport.update({
  id: '/local/$id',
  path: '/local/$id',
  getParentRoute: () => ElectionRoute,
} as any)
const ElectionPoliticianIdRoute = ElectionPoliticianIdRouteImport.update({
  id: '/politician/$id',
  path: '/politician/$id',
  getParentRoute: () => ElectionRoute,
} as any)
const ShareImageArticleSlugRoute = ShareImageArticleSlugRouteImport.update({
  id: '/share-image/article/$slug',
  path: '/share-image/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareImageDirectoryIdRoute = ShareImageDirectoryIdRouteImport.update({
  id: '/share-image/directory/$id',
  path: '/share-image/directory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareImageGallerySlugRoute = ShareImageGallerySlugRouteImport.update({
  id: '/share-image/gallery/$slug',
  path: '/share-image/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgArticleSlugRoute = ApiOgArticleSlugRouteImport.update({
  id: '/api/og/article/$slug',
  path: '/api/og/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blood': typeof BloodRoute
  '/chat': typeof ChatRoute
  '/date-converter': typeof DateConverterRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/election': typeof ElectionRouteWithChildren
  '/epaper': typeof EpaperRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/members': typeof MembersRoute
  '/patro': typeof PatroRoute
  '/preeti': typeof PreetiRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directory/$id': typeof DirectoryIdRoute
  '/election/$id': typeof ElectionIdRoute
  '/election/embed': typeof ElectionEmbedRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/member/$id': typeof MemberIdRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/election/local/$id': typeof ElectionLocalIdRoute
  '/election/politician/$id': typeof ElectionPoliticianIdRoute
  '/share-image/article/$slug': typeof ShareImageArticleSlugRoute
  '/share-image/directory/$id': typeof ShareImageDirectoryIdRoute
  '/share-image/gallery/$slug': typeof ShareImageGallerySlugRoute
  '/api/og/article/$slug': typeof ApiOgArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blood': typeof BloodRoute
  '/chat': typeof ChatRoute
  '/date-converter': typeof DateConverterRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/election': typeof ElectionRouteWithChildren
  '/epaper': typeof EpaperRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/members': typeof MembersRoute
  '/patro': typeof PatroRoute
  '/preeti': typeof PreetiRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directory/$id': typeof DirectoryIdRoute
  '/election/$id': typeof ElectionIdRoute
  '/election/embed': typeof ElectionEmbedRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/member/$id': typeof MemberIdRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/election/local/$id': typeof ElectionLocalIdRoute
  '/election/politician/$id': typeof ElectionPoliticianIdRoute
  '/share-image/article/$slug': typeof ShareImageArticleSlugRoute
  '/share-image/directory/$id': typeof ShareImageDirectoryIdRoute
  '/share-image/gallery/$slug': typeof ShareImageGallerySlugRoute
  '/api/og/article/$slug': typeof ApiOgArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blood': typeof BloodRoute
  '/chat': typeof ChatRoute
  '/date-converter': typeof DateConverterRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/election': typeof ElectionRouteWithChildren
  '/epaper': typeof EpaperRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/members': typeof MembersRoute
  '/patro': typeof PatroRoute
  '/preeti': typeof PreetiRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directory/$id': typeof DirectoryIdRoute
  '/election/$id': typeof ElectionIdRoute
  '/election/embed': typeof ElectionEmbedRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/member/$id': typeof MemberIdRoute
  '/politician/$id': typeof PoliticianIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/election/local/$id': typeof ElectionLocalIdRoute
  '/election/politician/$id': typeof ElectionPoliticianIdRoute
  '/share-image/article/$slug': typeof ShareImageArticleSlugRoute
  '/share-image/directory/$id': typeof ShareImageDirectoryIdRoute
  '/share-image/gallery/$slug': typeof ShareImageGallerySlugRoute
  '/api/og/article/$slug': typeof ApiOgArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blood'
    | '/chat'
    | '/date-converter'
    | '/directory'
    | '/election'
    | '/epaper'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/market'
    | '/members'
    | '/patro'
    | '/preeti'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/admin/gallery'
    | '/article/$slug'
    | '/category/$slug'
    | '/directory/$id'
    | '/election/$id'
    | '/election/embed'
    | '/gallery/$slug'
    | '/member/$id'
    | '/politician/$id'
    | '/api/auth/$'
    | '/election/local/$id'
    | '/election/politician/$id'
    | '/share-image/article/$slug'
    | '/share-image/directory/$id'
    | '/share-image/gallery/$slug'
    | '/api/og/article/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blood'
    | '/chat'
    | '/date-converter'
    | '/directory'
    | '/election'
    | '/epaper'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/market'
    | '/members'
    | '/patro'
    | '/preeti'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/admin/gallery'
    | '/article/$slug'
    | '/category/$slug'
    | '/directory/$id'
    | '/election/$id'
    | '/election/embed'
    | '/gallery/$slug'
    | '/member/$id'
    | '/politician/$id'
    | '/api/auth/$'
    | '/election/local/$id'
    | '/election/politician/$id'
    | '/share-image/article/$slug'
    | '/share-image/directory/$id'
    | '/share-image/gallery/$slug'
    | '/api/og/article/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blood'
    | '/chat'
    | '/date-converter'
    | '/directory'
    | '/election'
    | '/epaper'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/market'
    | '/members'
    | '/patro'
    | '/preeti'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/admin/gallery'
    | '/article/$slug'
    | '/category/$slug'
    | '/directory/$id'
    | '/election/$id'
    | '/election/embed'
    | '/gallery/$slug'
    | '/member/$id'
    | '/politician/$id'
    | '/api/auth/$'
    | '/election/local/$id'
    | '/election/politician/$id'
    | '/share-image/article/$slug'
    | '/share-image/directory/$id'
    | '/share-image/gallery/$slug'
    | '/api/og/article/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BloodRoute: typeof BloodRoute
  ChatRoute: typeof ChatRoute
  DateConverterRoute: typeof DateConverterRoute
  DirectoryRoute: typeof DirectoryRouteWithChildren
  ElectionRoute: typeof ElectionRouteWithChildren
  EpaperRoute: typeof EpaperRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MembersRoute: typeof MembersRoute
  PatroRoute: typeof PatroRoute
  PreetiRoute: typeof PreetiRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MemberIdRoute: typeof MemberIdRoute
  PoliticianIdRoute: typeof PoliticianIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ShareImageArticleSlugRoute: typeof ShareImageArticleSlugRoute
  ShareImageDirectoryIdRoute: typeof ShareImageDirectoryIdRoute
  ShareImageGallerySlugRoute: typeof ShareImageGallerySlugRoute
  ApiOgArticleSlugRoute: typeof ApiOgArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood': {
      id: '/blood'
      path: '/blood'
      fullPath: '/blood'
      preLoaderRoute: typeof BloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-converter': {
      id: '/date-converter'
      path: '/date-converter'
      fullPath: '/date-converter'
      preLoaderRoute: typeof DateConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/election': {
      id: '/election'
      path: '/election'
      fullPath: '/election'
      preLoaderRoute: typeof ElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patro': {
      id: '/patro'
      path: '/patro'
      fullPath: '/patro'
      preLoaderRoute: typeof PatroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preeti': {
      id: '/preeti'
      path: '/preeti'
      fullPath: '/preeti'
      preLoaderRoute: typeof PreetiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$id': {
      id: '/directory/$id'
      path: '/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof DirectoryIdRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/election/$id': {
      id: '/election/$id'
      path: '/$id'
      fullPath: '/election/$id'
      preLoaderRoute: typeof ElectionIdRouteImport
      parentRoute: typeof ElectionRoute
    }
    '/election/embed': {
      id: '/election/embed'
      path: '/embed'
      fullPath: '/election/embed'
      preLoaderRoute: typeof ElectionEmbedRouteImport
      parentRoute: typeof ElectionRoute
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/member/$id': {
      id: '/member/$id'
      path: '/member/$id'
      fullPath: '/member/$id'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politician/$id': {
      id: '/politician/$id'
      path: '/politician/$id'
      fullPath: '/politician/$id'
      preLoaderRoute: typeof PoliticianIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/election/local/$id': {
      id: '/election/local/$id'
      path: '/local/$id'
      fullPath: '/election/local/$id'
      preLoaderRoute: typeof ElectionLocalIdRouteImport
      parentRoute: typeof ElectionRoute
    }
    '/election/politician/$id': {
      id: '/election/politician/$id'
      path: '/politician/$id'
      fullPath: '/election/politician/$id'
      preLoaderRoute: typeof ElectionPoliticianIdRouteImport
      parentRoute: typeof ElectionRoute
    }
    '/share-image/article/$slug': {
      id: '/share-image/article/$slug'
      path: '/share-image/article/$slug'
      fullPath: '/share-image/article/$slug'
      preLoaderRoute: typeof ShareImageArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-image/directory/$id': {
      id: '/share-image/directory/$id'
      path: '/share-image/directory/$id'
      fullPath: '/share-image/directory/$id'
      preLoaderRoute: typeof ShareImageDirectoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-image/gallery/$slug': {
      id: '/share-image/gallery/$slug'
      path: '/share-image/gallery/$slug'
      fullPath: '/share-image/gallery/$slug'
      preLoaderRoute: typeof ShareImageGallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/article/$slug': {
      id: '/api/og/article/$slug'
      path: '/api/og/article/$slug'
      fullPath: '/api/og/article/$slug'
      preLoaderRoute: typeof ApiOgArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DirectoryRouteChildren {
  DirectoryIdRoute: typeof DirectoryIdRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryIdRoute: DirectoryIdRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

interface ElectionRouteChildren {
  ElectionIdRoute: typeof ElectionIdRoute
  ElectionEmbedRoute: typeof ElectionEmbedRoute
  ElectionLocalIdRoute: typeof ElectionLocalIdRoute
  ElectionPoliticianIdRoute: typeof ElectionPoliticianIdRoute
}

const ElectionRouteChildren: ElectionRouteChildren = {
  ElectionIdRoute: ElectionIdRoute,
  ElectionEmbedRoute: ElectionEmbedRoute,
  ElectionLocalIdRoute: ElectionLocalIdRoute,
  ElectionPoliticianIdRoute: ElectionPoliticianIdRoute,
}

const ElectionRouteWithChildren = ElectionRoute._addFileChildren(
  ElectionRouteChildren,
)

interface GalleryRouteChildren {
  GallerySlugRoute: typeof GallerySlugRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GallerySlugRoute: GallerySlugRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BloodRoute: BloodRoute,
  ChatRoute: ChatRoute,
  DateConverterRoute: DateConverterRoute,
  DirectoryRoute: DirectoryRouteWithChildren,
  ElectionRoute: ElectionRouteWithChildren,
  EpaperRoute: EpaperRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MembersRoute: MembersRoute,
  PatroRoute: PatroRoute,
  PreetiRoute: PreetiRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  MemberIdRoute: MemberIdRoute,
  PoliticianIdRoute: PoliticianIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ShareImageArticleSlugRoute: ShareImageArticleSlugRoute,
  ShareImageDirectoryIdRoute: ShareImageDirectoryIdRoute,
  ShareImageGallerySlugRoute: ShareImageGallerySlugRoute,
  ApiOgArticleSlugRoute: ApiOgArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
